services:
    backend:
        build:
            context: ./backend
            dockerfile: dockerfile
        volumes:
            - ./backend/app:/rero/app
        ports:
            - 8080:8080
            - 8081:8081
            - 8082:8082
        tty: true
        network_mode: host

    frontend:
        build:
            context: ./frontend
            dockerfile: dockerfile
        ports:
            - 3000:3000
        tty: true
        network_mode: host
 