services:
    backend:
        build:
            context: ./backend
            dockerfile: dockerfile
        volumes:
            - ./backend/app:/rero/app
        ports:
            - 8080:8080
            - 8081:8081
            - 8082:8082
        tty: true
        # TODO: Change to overlay network for docker swarm  & security
        network_mode: host

    frontend:
        depends_on:
            - backend
        build:
            context: ./frontend
            dockerfile: dockerfile
        ports:
            - 80:3000
        tty: true
        # TODO: Change to overlay network for docker swarm & security
        network_mode: host
 