services:
    backend:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - ./app:/rero/app
        ports:
            - 8080:8080
            - 8081:8081
            - 8082:8082
        tty: true
        # TODO: Change to overlay network for docker swarm  & security
        network_mode: host
 