services:
    app:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - ./app:/rero/app
            - ./http:/srv/http
        ports:
            - 8080:8080
            - 8081:8081
        tty: true
        network_mode: host
 